#include <util.h>

#define ERR_STAGE2_SUCCESS 0
#define ERR_STAGE2_FAILED_TO_OPEN_PROCESS 50
#define ERR_STAGE2_FAILED_TO_WAIT_FOR_PROCESS 51
#define ERR_STAGE2_FAILED_TO_DELETE_LOADER 52
#define ERR_STAGE1_FAILED_TO_OPEN_DRIVER 53
#define ERR_STAGE1_INVALID_DRIVER_VERSION 54
#define ERR_STAGE2_INVALID_MAGIC 100
#define ERR_STAGE2_INVALID_VERSION 101
#define ERR_STAGE2_FAILED_TO_CREATE_THREAD 102
#define ERR_STAGE2_FAILED_TO_WAIT_FOR_MODULE 103