#pragma once

#define FUMO_DRIVER_VERSION 0x00000001
#define FUMO_HOOKED_DRIVER_NAME L"\\Driver\\Null"
#define FUMO_HOOKED_DRIVER_NAME_USER L"\\\\.\\NUL"

#define IO_VERSION_REQUEST CTL_CODE(FILE_DEVICE_UNKNOWN, 0x8000, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IO_UNLOAD_REQUEST CTL_CODE(FILE_DEVICE_UNKNOWN, 0x8001, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IO_ALLOC_REQUEST CTL_CODE(FILE_DEVICE_UNKNOWN, 0x8011, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IO_MAP_MEMORY_REQUEST CTL_CODE(FILE_DEVICE_UNKNOWN, 0x8012, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IO_EXECUTE_REQUEST CTL_CODE(FILE_DEVICE_UNKNOWN, 0x8013, METHOD_BUFFERED, FILE_ANY_ACCESS)

typedef struct _IO_VERSION_RESPONSE_DATA {
    ULONG Version;
} IO_VERSION_RESPONSE_DATA, *PIO_VERSION_RESPONSE_DATA;

typedef struct _IO_ALLOC_REQUEST_DATA {
    ULONG Size;
} IO_ALLOC_REQUEST_DATA, *PIO_ALLOC_REQUEST_DATA;

typedef struct _IO_ALLOC_RESPONSE_DATA {
    PVOID Address;
} IO_ALLOC_RESPONSE_DATA, *PIO_ALLOC_RESPONSE_DATA;

typedef struct _IO_MAP_MEMORY_REQUEST_DATA {
    ULONG Pid;
    PVOID Address;
    ULONG Size;
} IO_MAP_MEMORY_REQUEST_DATA, *PIO_MAP_MEMORY_REQUEST_DATA;

typedef struct _IO_EXECUTE_REQUEST_DATA {
    ULONG Pid;
    PVOID Address;
    PVOID Argument;
} IO_EXECUTE_REQUEST_DATA, *PIO_EXECUTE_REQUEST_DATA;